WordPress/openverse-api

- ingestion_server/README.md
- ingestion_server/publish_release.sh
- Switch from `creativecommons` to `openverse` docker hub account
- Add documentation about deploying the ingestion server to docker in the ingestion server README
> Ingestion server Docker improvements

- CONTRIBUTING.md
- CONTRIBUTORS.md
- DOCUMENTATION_GUIDELINES.md
- README.md
- analytics/docs/swagger.yaml
- openverse-api/catalog/api/views/site_views.py
- openverse-api/catalog/urls.py
Small email address and directory name typo fixes: 
- Replace all referenced email addresses with `zack.krida@automattic.com` for now.
- `ccatalog-*` ~> `openverse-*`
> Small email address and directory name typo fixes

- openverse-api/catalog/scripts/api_load_testing/locustfile.py
- openverse-api/catalog/scripts/thumbnail_load_test/locustfile.py
- openverse-api/catalog/settings.py
- openverse-api/test/api_live_integration_test.py
- openverse-api/test/api_live_search_qa.py
- openverse-api/test/v1_integration_test.py
Quick fix to replace the `dev.api.openverse.engineering` with `api-dev.openverse.engineering` because Cloudflare SSL doesn't work on nested subdomains (i.e `sub.sub.sub.domain.com`).
> Domain hotfix

- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/cleanup.py
- ingestion_server/ingestion_server/distributed_reindex_scheduler.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/indexer_worker.py
- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/tasks.py
- ingestion_server/test/integration_tests.py
- openverse-api/catalog/api/models/media.py
- openverse-api/catalog/api/serializers/image_serializers.py
- openverse-api/catalog/api/serializers/link_serializers.py
- openverse-api/catalog/api/utils/ccrel.py
- openverse-api/catalog/api/utils/validate_images.py
- openverse-api/catalog/api/utils/watermark.py
- openverse-api/catalog/api/views/image_views.py
- openverse-api/catalog/api/views/site_views.py
- openverse-api/catalog/scripts/api_load_testing/locustfile.py
- openverse-api/catalog/scripts/migration/migrate_lists.py
- openverse-api/test/api_live_integration_test.py
- openverse-api/test/api_live_search_qa.py
- openverse-api/test/search_qa_test.py
- openverse-api/test/v1_integration_test.py
Python 3.6 introduced a new way of formatting strings using so-called f-strings. This made formatted strings more readable and concize.
Instead of writing 
```python
who = "world"
print("Hello {who}".format(who=who))
```
we can write 
```python
who = "world"
print(f"Hello {who}")
```
This PR consistently replaces `string.format` with `f-strings`.
Signed-off-by: Olga Bulat <obulat@gmail.com>
> Replace `string.format()` with `fstrings`

- analytics/server.py
- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/indexer_worker.py
Fixes #114 
Falcon version 3.0 deprecated `falcon.API` class, and replaced it with `falcon.App`. This PR uses the new way of creating the falcon App.
> Replace deprecated `falcon.API` with `falcon.App`

- openverse-api/catalog/api/migrations/0032_audio_models.py
- openverse-api/catalog/api/models/audio.py
The PR #81 failed CI checks **after** being merged. This PR addresses those check failures.
> Fix CI issues is audio models

- .gitignore
- docker-compose.yml
- ingestion_server/Dockerfile
- ingestion_server/Dockerfile-worker
- ingestion_server/ingestion_server/state.py
This PR updates the ingestion server `Dockerfile` and the project `docker-compose.yml` file to bind-mount the ingestion-server codebase from the repository instead of copying the code during image build. This allows code changes to reflect immediately in the container instead of needing a rebuild everytime.
As a side-effect, two binary files named `db` and `lock` get created in the repo which should not be Git tracked so they have been `.gitignore`-d.
Also this PR makes the `Dockerfile` symmetrical with the API `Dockerfile`, which is good.
> Update Docker image for ingestion-server to use bind mounts properly

- ingestion_server/test/generate_integration_test_docker_compose.py
- ingestion_server/test/integration-test-docker-compose.yml
- ingestion_server/test/integration_tests.py
Related to #143 and #104.
When executing integration tests (steps in [README][readme_ref] file) of the ingestion-server, the **integration-ingestion** service cannot start correctly due to source files not being mounted in the docker container. The error in the logs appeared as:
```
INFO:root:Waiting for ingestion server to come up...
integration-ingestion_1  | Error: could not find config file config/supervisord.conf
integration-ingestion_1  | For help, use /usr/bin/supervisord -h
test_integration-ingestion_1 exited with code 2
INFO:root:Waiting for ingestion server to come up...
INFO:root:Waiting for ingestion server to come up...
INFO:root:Waiting for ingestion server to come up...
INFO:root:Waiting for ingestion server to come up...
INFO:root:Waiting for ingestion server to come up... …
```
> Modify docker-compose file for Ingestion-server's integration tests

- docker-compose.yml
Docker v3.5.2 (66501) with Compose v1.29.2 raises warnings about empty environment variables. 
```
WARN[0000] The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string. 
WARN[0000] The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string. 
```
This PR suppresses those warnings by explicitly setting the blank strings.
> Suppress warning about blank env vars

- .github/workflows/integration-tests.yml
This PR uses the action `satackey/action-docker-layer-caching` to cache Docker layers between workflow runs. This should considerably speed up the integration tests.
> Add caching to speed up integration tests

- openverse-api/catalog/api/migrations/0032_audio_models.py
- openverse-api/catalog/api/models/audio.py
- openverse-api/catalog/api/serializers/audio_serializers.py
This PR adds the 'sound_effect' category in the model, migration and serializer. The migration `0032_audio_models.py` has been modified instead of creating a new one because the change hasn't gone into production.
> Add the `sound_effect` category

- .github/workflows/integration-tests.yml
<s>Fixes</s> Addresses #236
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best …
```
> Improved lint check speed

- openverse_api/test/README
Fixes #261 by @zackkrida
This PR 
- removes the `test/README` file due to redundant informations
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```
> Removing redundant `test/README`

- .github/workflows/integration_tests.yml
- .gitignore
- docker-compose.yml
- justfile
Fixes #259 by @dhruvkb
This PR adds a new `just` recipe, `wait-until-healthy`, which waits for the services to complete their healthchecks before finishing. This recipe is then a dependent for all other recipes that require the services to be up prior to running.
I've also modified the integration test GHA so it uses the `just init` recipe rather than the 3 separate steps. If we'd prefer to have more granularity in steps there, I'm happy to revert that.
When I launched the stack on my machine, all of my memory was immediately allocated. Elasticsearch ended up taking **16 GB** of RAM :scream:. I added a limit to the `docker-compose.yml` of 4GB, which I believe should be sufficient for ES. It can be overridden with the `ES_MEM_LIMIT` environment variable, including removing the limit …
> Add just recipe to wait for stack startup

- ingestion_server/ingestion_server/indexer.py
- ingestion_server/test/integration_test.py
Fixes #361 by @AetherUnbound
This PR adds the `deleted` and `mature` existence columns for the query which pulls records in order to update elasticsearch. It also adds tests which run the `UPDATE_INDEX` action for both images & audio.
`just ing-testlocal`
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```
> Include deleted & mature existence checks when updating indices

- openverse_api/catalog/api/views/media_views.py
Signed-off-by: Olga Bulat <obulat@gmail.com>
Fixes #393 by @obulat
This PR sets the page_size for `/related/` endpoint to a constant of 10. This is not elegant, the constant should probably be set elsewhere, but I'm not familiar enough with the API codebase to find the correct place.
Run the api (just up/just init), and then go to `http://localhost:8000/v1/images/41d51a9c-cdf5-4ca6-acfc-ebd63f807ecf/related/` 
You should see that although the result count is over 1200, the page_size is set to 10, and there is no error.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> Fix page_size setting for related media

- openverse_api/catalog/api/utils/pagination.py
Fixes an issue we've seen in production.
We don't have tests for this yet, but I was able to check locally that a search which was previously erroring out is now returning results.
`just up`, then access this URL: http://localhost:8000/v1/images/?page=NaN&shouldPersistMedia=true&q=wolf
<details>
```
Version 1.1
Suite D4700
By making a …
```
> Check if value is numeric before converting to int

- ingestion_server/README.md
- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/queries.py
- ingestion_server/mock_schemas/audio.sql
- ingestion_server/mock_schemas/image.sql
- ingestion_server/test/gen_integration_compose.py
- ingestion_server/test/integration_test.py
- ingestion_server/test/mock_schemas/README.md
- ingestion_server/test/mock_schemas/audio.sql
- ingestion_server/test/mock_schemas/audioset.sql
- ingestion_server/test/mock_schemas/image.sql
- ingestion_server/test/run_test.sh
- justfile
Fixes #362 by @AetherUnbound
This PR modifies the ingestion server so that it renames the indices of the target table back to the original during the go-live table swap. Previously this was not occurring, and so every subsequent run would add a `temp_import_` prefix to the target table (ultimately this would result in something like `temp_import_temp_import_temp_import_unique_url_idx`). The ingestion server now retains information about the original index names and uses them to rename the indices after the old target table has been removed. The integration tests will now also verify that the indices are unchanged after a data refresh.
Indices must unique globally across a database, but constraints need not be. While no logic change is necessary, I've also added a constraint check during …
> Rename indices back to original during data refresh

- analytics/tests.py
- load_sample_data.sh
- openverse_api/catalog/api/examples/image_requests.py
- openverse_api/catalog/api/examples/image_responses.py
- openverse_api/catalog/api/utils/validate_images.py
- openverse_api/test/auth_test.py
- openverse_api/test/dead_link_filter_test.py
- openverse_api/test/image_integration_test.py
- openverse_api/test/v1_integration_test.py
Fixes #270 by @dhruvkb 
This PR adds new sample data for images with `category`, `filesize` and `filetype` columns filled. The data comes from the recently updated Flickr and StockSnap scripts (2500 rows each) using this query on the catalog DB:
```sql
SELECT
identifier, created_on, updated_on, ingestion_type, provider, source, 
foreign_identifier, foreign_landing_url, url, thumbnail, width, height, filesize
license, license_version, creator, creator_url, title, meta_data, tags, watermarked,
last_synced_with_source, removed_from_source, filetype, category, standardized_popularity
FROM (
SELECT *, ROW_NUMBER() OVER (
PARTITION BY provider ORDER BY standardized_popularity DESC
) AS row_num
FROM image_view
) AS T
WHERE row_num <= 2500;
```
I also updated the tests accordingly. The only test …
> Update sample data for images with missing columns filled

- openverse_api/catalog/api/serializers/audio_serializers.py
This PR fixes a missing keyword argument in `ListField` which gives warnings or errors in CI. This was contributed in several PRs
- #411 
- #427 
- #429 
so merging it separately while removing it from the PRs would prevent them from "eventually conflicting".
`serializers.ListField` requires that the child-field be passed as a keyword argument 'child' and not as a positional argument. This requirement is addressed by the PR.
Passing CI is sufficient.
<details>
```
Version 1.1
Suite D4700 …
```
> Add kwarg 'child' required by `seriaizers.ListField`

- ingestion_server/README.md
- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/slack.py
- ingestion_server/ingestion_server/tasks.py
- ingestion_server/test/env.integration
Fixes #412 by @AetherUnbound
This PR adds a very simple slack notification mechanism for the ingestion server. During data refresh, the ingestion server will give periodic updates in slack regarding the progress of a given data refresh. If the refresh fails at any point, the ingestion server will also send the exception to Slack.
1. Set the `SLACK_WEBHOOK` variable in `env.docker`
1. Spin up the stack
1. Run `just ingest-upstream`
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```
> Data refresh slack notifications

- .github/workflows/ci_cd.yml
An [attempt to publish v2.1.0](https://github.com/WordPress/openverse-api/actions/runs/1655014806) did not successfully trigger the Docker image publishing, instead that step was skipped. Based on actions/runner#950 and the [`github` object context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), I believe it was because we were referencing `github.event` (an `object`) rather than `github.event_name` (a string).
We will have to try another publish and see if it works!
<details>
```
Version 1.1
1 …
```
> Use event_name over event for publish conditional

- ingestion_server/test/env.integration
Fixes #447 by @AetherUnbound
This PR resolves an issue wherein the integration tests were failing after running `just env`. It turns out that [the decouple library](https://pypi.org/project/python-decouple/#env-file) (which is being used to [initialize the `RELATIVE_UPSTREAM_DB_*` variables](https://github.com/WordPress/openverse-api/blob/a7aa53ffc5f9d3b8b6bebf9dbacba248623a5a61/ingestion_server/ingestion_server/ingest.py#L43-L54)) was picking up the variables in the `.env` file created under the `ingestion_server` directory. Since `RELATIVE_UPSTREAM_DB_*` is explicitly defined in the `env.template` file, it was overriding the default, which would normally fall back to the `UPSTREAM_DB_*` values. Since the services are named differently for integration tests, this would then cause the …
> Override default RELATIVE_UPSTREAM_DB_* vars for integration tests

- analytics/.dockerignore
- analytics/Dockerfile
- api/.dockerignore
- api/Dockerfile
- docker-compose.yml
- ingestion_server/.dockerignore
- ingestion_server/Dockerfile
- justfile
Presently, we are unable to launch the ingestion server in production using only the published image. The current setup assumes that the operational files will be mounted into the containers when they are spun up, which may not be the case for all services running in production.
This PR adds steps in each `Dockerfile` to copy all of the necessary operational files into the image so they are available for the container on its own.  Images can now be spun up on their own and run successfully without any attached volumes. This ensures that the images that are pulled from our container registry can be launched directly without requiring a copy of the code locally. It also means that our final images are immutable (at least in production), so we won't have any unexpected changes at runtime …
> Copy operational files into final docker images

- ingestion_server/README.md
- ingestion_server/docker-compose.yml
This PR corrects the docker repository name used in production for the ingestion server. This format changed as a part of #437. It also adds a way to easily override the desired tag using an environment variable (in this case, in the local `.env` file on production). This way we can specify which version we want to pull/run without having to update the file on every version bump.
Lastly, I added some documentation to the DNS segment based on discussion in #346.
1. `cd ingestion_server`
1. `docker-compose pull` (optionally setting the `IMAGE_TAG` variable to a specific version tag, e.g. `v2.1.1`)
1. `docker-compose up -d`
<details> …
> Correct docker repository for the ingestion server, update docs

- api/catalog/api/models/audio.py
Currently the API raises an error when accessing the thumbnail for an audio which has no audio set mapped to it. This PR fixes that error by wrapping the `.get` call in a `try...except` block.
0. Check out the PR and run the server.
1. Access the thumbnail for an audio from the Wikimedia provider. Those usually don't belong to any audio set.
2. See a 404 error; before the PR it would have been a 500 error.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
> Handle error when audio set does not exist

- .github/workflows/ci_cd.yml
Hotfix PR for an issue we were seeing when [publishing v2.2.0](https://github.com/WordPress/openverse-api/runs/4808338411?check_suite_focus=true) wherein the docker images were being rebuilt when running the tests (rather than using the artifacts produced upstream).
This updates the tags that get pushed when the artifact is initially created to also contain the `openverse-` prepended piece.
I'm hoping we'll see this with the CI/CD runs on this PR since they were likely happening there as well.
<details>
```
Version 1.1
1 Letterman …
```
> Publish artifacts with prepended `openverse-` tags

- api/catalog/logger.py
- api/catalog/settings.py
This PR adds some additional logging configuration to enable exception logging in production. Currently, when an exception or error occurs, we get unhelpful logs that look like this:
```
2022-01-07T13:06:57.964-08:00	Internal Server Error: /v1/audio/
2022-01-07T13:06:57.965-08:00	Internal Server Error: /v1/audio/
2022-01-07T13:06:57.984-08:00	Internal Server Error: /v1/audio/
2022-01-07T13:06:57.985-08:00	Internal Server Error: /v1/audio/
```
The above errors are HTTP 500 errors, but we aren't able to see any information about what is actually failing. The logging configuration in this PR ensures that:
1. Intentional logging within the service gets bubbled up appropriately
1. Django logging in general is set to `WARNING` in production
1. Exceptions are bubbled up to the logs appropriately …
> Add logger configuration to allow prod exception handling

- api/catalog/settings.py
- api/env.template
Fixes #475 by @sarayourfriend 
Replace `PYTHON_ENV` with the already used `ENVIRONMENT`.
Checkout the branch and update your local instance (`just recreate && just init` should do it but will wipe local data) and verify the API runs.
Unit tests should also pass of course.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
> Use the existing and configured env indicator

- ingestion_server/ingestion_server/slack.py
- ingestion_server/test/unit_tests/test_slack.py
Fixes #473 by @AetherUnbound
This is a small PR which adds the running environment to the data refresh slack alert username. This will help us distinguish which runs are occurring in production and which are in staging/other environments.
I also added tests for this module, now that I've improved the testing setup in #474!
`just ing-testlocal`
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
> Add environment to data refresh slack alert username

- .github/workflows/ci_cd.yml
Fixes #443 by @dhruvkb
This PR removes the `main` constraint for PR triggers in the CI/CD workflow so that all PRs run the docker building, testing, and integration test steps.
We could potentially open a PR _onto_ this PR if we wanted to test that it works.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
> Run CI/CD on every pull request

- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/slack.py
- ingestion_server/ingestion_server/tasks.py
- ingestion_server/test/unit_tests/test_slack.py
Fixes #481 by @AetherUnbound 
Adds Slack logging levels to the ingestion server; this lets us easily control the granularity of logging we need in a given environment. 
* Introduces `slack.error`, `slack.info`, and `slack.verbose` functions
* `verbose` to be used for 'less important' messages; this allows an environment set at `INFO` to receive the most important info messages (data refresh start/stop) without triggering too many notifications.
* I didn't use `trace`  for this because my understanding is that implies sensitive data and should not be used in production
* We could easily add `warning`, `debug` etc if those become useful
* Updates existing slack notifications to use the new levels
The level is set using the `SLACK_LOG_LEVEL` environment variable. 
Notes/open questions:
* If …
> Add logging levels to Slack notifications in ingestion server

- api/Pipfile
- api/Pipfile.lock
- api/catalog/api/models/audio.py
- api/catalog/management/commands/generatewaveforms.py
- api/test/factory/faker.py
- api/test/factory/models/audio.py
- api/test/factory/models/media.py
- api/test/run_test.sh
- api/test/unit/management/commands/generatewaveforms_test.py
- api/test/unit/models/audio_test.py
Fixes #529 by @AetherUnbound
This PR adds a Django command, `generatewaveforms`, for generating waveforms of all audio records in order to populate the waveform cache.
I've added a new dependency, [`django-tqdm`](https://pypi.org/project/django-tqdm/), to make the output easier to read. We can remove this dependency once the API no longer generates waveforms.
**Command list**
```bash
root@c219265a4b39:/api# python manage.py --help
Type 'manage.py help <subcommand>' for help on a specific subcommand.
Available subcommands:
[auth]
changepassword
createsuperuser
[catalog]
generatewaveforms
[contenttypes]
remove_stale_contenttypes
...
```
**Help text**
```bash
root@c219265a4b39:/api# python manage.py generatewaveforms --help
usage: manage.py generatewaveforms [-h] [--version] [-v {0,1,2,3}] …
```
> Django command for generating waveforms

- api/catalog/api/serializers/media_serializers.py
This PR sends `tags` as a blank array `[]` if the media does not have any tags instead of not sending the field at all.
1. Run the API on main and find media without `tags` in the search.
2. Checkout the PR and run the API.
3. Search for audio again.
4. See the same media with `tags` as a blank array.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
> Send `[]` if media has no tags

- api/Pipfile
- api/Pipfile.lock
- api/catalog/api/utils/throttle.py
- api/test/factory/faker.py
- api/test/factory/models/oauth2.py
- api/test/run_test.sh
- api/test/unit/utils/throttle_test.py
Fixes #565 by @zackkrida 
Adds the ability to easily define exemptions for throttle classes via a general DRF/Django OOP inspired approach.
The idea is that each exemption is defined as its own class which implements the `is_exempt` method which returns a boolean: true when exempt and false otherwise. If any exemption class declares the request as exempt from throttling, then the throttle's `allow_request` logic is short circuited and the request is allowed.
I've added comprehensive unit tests for this. I tried to cover every possible configuration and request situation with redundant checks against the pre-existing state before checking the requests.
The tests are roughly modeled after DRF's own tests for the base throttling classes: …
> Add throttle exemptions

- api/catalog/api/docs/audio_docs.py
- api/catalog/api/docs/image_docs.py
The reporting endpoints for audio and image had the `query_serializer` set on the Swagger operation. This caused the schema of the data sent in the POST body to be shown as the query parameters.
Screenshot on `main`:
By removing the `query_serializer`, this duplication is gone and the information appears in the correct location.
Screenshot from PR:
0. Check out the PR and run the services using `just up`.
1. Visit the API docs for the image and audio report endpoints.
<details>
```
Version 1.1
Suite D4700
San …
```
> Remove `query_serializer` for reporting endpoints

- api/test/audio_integration_test.py
- api/test/media_integration.py
Related to #583 by @obulat
Add an automated test to complement the fix and cover the bug.
Run the following commands in the `main` branch, note that it fails, and then try on this branch.
```
just up
docker-compose exec web bash
./test/run_test.sh test/audio_integration_test.py
```
<details>
```
Version 1.1
Suite D4700
By making a …
```
> Replace plural `categories` as field name with singular `category`

- justfile
Addresses an issue that was introduced in #580
This PR re-adds a parameter to the `just api-test` recipe so that the API tests can run appropriately. When the `web` service was not specified, the recipe dependencies would run and then the recipe would exit out without an error code as soon as it hit the `docker-compose exec ./test/run_test.sh` step.
`just api-test` should run tests appropriately and display testing output.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
> Specify service when running test recipe

- .github/workflows/ci_cd.yml
- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/distributed_reindex_scheduler.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/indexer_worker.py
- ingestion_server/ingestion_server/state.py
- ingestion_server/ingestion_server/tasks.py
Fixes #592 by @stacimc
This PR updates the ingestion server to track the status of distributed reindexer workers, and more accurately report the 'active' status of the data refresh task.
Locally, the data refresh task is entirely synchronous. In staging and production, the elasticsearch reindexing step is distributed across worker tasks. The data refresh task schedules this work, then immediately exits. When you poll the ingestion server to check on the status of the task, it reports that it is inactive because the task has completed, even though distributed work is ongoing.
This PR basically:
* adds an `active_workers` property to the already tracked `TaskStatus`, which is by default 'False' when a task is created.
* if we're in staging or production, we'll set this to `True` before …
> Accurately report status of data_refresh when work is distributed

- api/Dockerfile
- api/catalog/api/views/image_views.py
This PR moves the imports for XMP modules from the top-level into a function. This prevents the watermark-specific libraries from being imported unless they actually need to be used (_read "never"_) and allows running the server on the host directly, without neededing to install any Exempi libraries on the host.
This makes it easy to run a dev setup outside the container which makes it fast and easy to restart, attach debuggers etc.
0. Orchestrate all servers using `just up`. Stop the web service using `docker-compose stop web`.
1. Rename `env.template` to `.env` so that Pipenv can read it automatically.
2. Run the Django dev server on the host, using `pipenv run python manage.py runserver`.
3. You should be able to run it directly without needing `exempi` or `libexempi` or anything of …
> Make Exempi library optional for local setup

- .github/workflows/push_docker_image.yml
- api/docs/guides/index.md
- api/docs/guides/publish.md
- api/docs/guides/test.md
Fixes #597 by @AetherUnbound
This PR adds the ability to tag a Docker image artifact by SHA only and push it to our container registry. The workflow is manually triggered and requires an input on which image to push (only one option is allowed because we are almost never making changes to _both_ the API and ingestion server images). 
The example use case for this: We've made a change to one of the services, and want to deploy it on staging. Our deployment process requires (or will soon require) a tagged Docker image to deploy. Running this workflow will tag and push an image by SHA only, so `latest` is unaffected. We can then deploy by pointing to said commit.
I'm going to test this in this PR!
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commi …
> Add manually triggered action for pushing docker image by SHA

- .github/workflows/build_imaginary.yml
Update h2non/bimg from 1.1.7 to 1.1.9 to enable support for GIF export.
> Update bimg version in imaginary Docker image

- .github/workflows/ci_cd.yml
- justfile
Fixes #631 by @dhruvkb
This PR adds step to run Django check in CI.
View the CI logs to see that Django checks have been run successfully.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
> Add step to run Django check in CI

- api/catalog/settings.py
In some recent infrastructure troubleshooting, we found that our email client was attempting to connect on the default port (`25`) and connection attempts were timing out. We changed this to port `587`, a more secure SMTP port, and the client worked correctly. Since most mail clients use or require SSL/TLS, it seemed prudent to update this default to reflect that.
1. `just dj shell`
1. `from django.conf import settings`
1. Check that `settings.EMAIL_PORT` now shows 587
<details>
```
Version 1.1
Suite D4700
San …
```
> Change default email port to 587

- api/catalog/api/serializers/media_serializers.py
This PR fixes an error raised by the `TagSerializer` when supplied with an empty list `[]` as the instance to serialize. This default was earlier added to ensure that the value of the `tag` key is always a list but that goal can be achieved in a better way by overriding `to_representation`.
Error first [reported](https://wordpress.slack.com/archives/C02012JB00N/p1651526277141779) in Slack by @AetherUnbound 
0. Check out the PR and run the API services.
1. Make some API calls to `/v1/images`.
2. This error should not appear in the logs. 
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Override `to_representation` instead of setting default

- api/catalog/settings.py
Fixes #676  by @AetherUnbound 
Adds the setting from the issue.
:shrug: Not sure how to test this locally. You could set the environment variable then use `manage.py shell` to check if it is set.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Add DEFAULT_FROM_EMAIL setting handling

- api/docs/guides/index.md
- api/docs/guides/publish.md
This PR fixes an issue I noticed in #678 where the `https.md` guide was not showing in the table of contents. It also corrects a warning that had shown up in the sphinx output:
```
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] guides/publish                                                                                                                                                                            
looking for now-outdated files... none found
pickling environment... done
checking consistency... /api/docs/guides/https.md: WARNING: document isn't included in any toctree     <-- here
done
preparing documents... done
writing output... [100%] index …
```
> Add HTTPS doc to table of contents, fix warning

- api/catalog/api/utils/oauth2_helper.py
This PR fixes a circular import that was inadvertently added in #633. The circular import occurred only when `DISABLE_GLOBAL_THROTTLING` was set to `False`. Deferring the reference to `ThrottledApplication` appears to have resolved the import issue.
1. Add `DISABLE_GLOBAL_THROTTLING=FALSE` to `api/env.docker`
1. `just up`
1. Observe that the following error **does not** occur:
<details> <summary>Circular Import Error</summary>
```
web_1         | [2022-05-05 18:22:46 +0000] [14] [ERROR] Exception in worker process
web_1         | Traceback (most recent call last):
web_1         |   File "/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
web_1         |     return import_string(val)
web_1         |   File …
```
> Defer ThrottledApplication reference

- .github/workflows/ci_cd.yml
Follow up to #683.
There are cases (e.g. during a release on a tag, or a workflow dispatch on an open branch without a pull request) where we want the CI/CD pipeline to run but we do not want a docs preview generated. The previous conditional was insufficient in covering these cases. Since we really only want to have a docs preview on pull requests, this PR updates the workflow to only run said step during pull requests!
I will attempt a workflow dispatch of this branch once the PR is open to see if the docs preview is run then.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
```
> Only run the docs preview on pull requests

- api/catalog/management/commands/resendoauthverification.py
- api/test/factory/models/oauth2.py
- api/test/unit/management/commands/resendoauthverification_test.py
Fixes #689 by @AetherUnbound  
Adds a new command to run for resending verification emails. Note: I haven't written unit tests for this but I need to stop working on this for the day and come back to it tomorrow. Just wanted to get a draft up early.
I tried to write comprehensive unit tests. If you notice a missing branch please let me know so I can add additional tests.
You can test this on your local API (though I'm hoping the unit tests are sufficient) by setting the email backend to SMTP in your API settings without filling in the SMTP server information and then making some registration requests with multiple application names. Use a mix of the same email and different emails. This will cause the verifications to be completed, but because we haven't filled in the SMTP server …
>  Add command to resend verification emails

- api/catalog/api/admin.py
Related to https://github.com/WordPress/openverse-catalog/issues/354
When an image is reported by a user through the `Report Content` feature, the reports become available for review in the `Image reports` admin page (http://localhost:8000/admin/api/imagereport/). When an audio file is reported, a similar report is created in the DB, but it isn't easily accessible through the Django Admin.
This PR adds an `Audio reports` admin page. It pulls out the existing code into an abstract MediaReportAdmin that can be used as additional models are added.
Visit both [Image](http://localhost:8000/admin/api/imagereport/) and [Audio](http://localhost:8000/admin/api/audioreport/) report admin pages and verify they work as normal (described below).
If you don't have any Image or Audio reports, you'll …
> Add AudioReports to the Django admin

- .github/workflows/ci_cd.yml
- api/catalog/custom_auto_schema.py
Fixes #722 by @AetherUnbound 
This PR fixes an error introduced in #699 that prevented the ReDoc pages from showing up. This is because the value of the field `page_query_param` is expected to be a string.
By setting pagination params to an empty list, this problem goes away.
0. Check out the PR and start the server.
1. Visit ReDoc at `http://localhost:8000/v1`.
2. See the pages without any errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
> Fix issue due to `page_query_param` not being a string

- .github/workflows/pr_closed.yml
Follow up on #747, additionally for the action that runs when a PR is closed. This was failing for the dependabot PRs: [[1]](https://github.com/WordPress/openverse-api/runs/6816938250?check_suite_focus=true) [[2]](https://github.com/WordPress/openverse-api/runs/6815499390?check_suite_focus=true) [[3]](https://github.com/WordPress/openverse-api/runs/6801480540?check_suite_focus=true)
We'll have to see! It worked for the publish step though so I suspect it should work for the close PR step :slightly_smiling_face:
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> Ensure that the docs cleanup step only runs on PRs that have permission

- ingestion_server/ingestion_server/ingest.py
- ingestion_server/test/integration_test.py
Fixes #752 by @AetherUnbound
This PR splits the index application & constraint remapping steps into separate, loggable executions so that we can determine how long each step takes during the data refresh.
I also improved the output of the integration tests a bit by removing colors that don't show up well in things that aren't a terminal.
1. Run `just ing-testlocal`
1. Open `ingestionserver/test/ingestion_logs.txt`
1. Observe the following lines (or similar) for each of the models:
```
integration_ingestion_server_1  | 2022-06-10 23:53:48,940 INFO ingest.py:348 - Copying finished! Recreating database indices...
integration_ingestion_server_1  | 2022-06-10 23:53:48,943 INFO ingest.py:353 - Running: CREATE UNIQUE INDEX temp_import_api_audioset_url_key ON public.temp_import_audioset USING …
```
> Log each index & constraint step

- api/catalog/api/serializers/audio_serializers.py
- api/test/audio_integration_test.py
Fixes #528 by @zackkrida.
Should also fix WordPress/openverse-frontend#1475
Adds a check to the `AudioSerializer` if the underlying audio row has artwork and removes the link in the case is not found. I believe we should make sure the cover of the album (if exists) is duplicated in each track if that track does not have its own artwork. In fact, I find it rare the case where the audio will have a different cover than their album.
This also seems to be the common case with our current live data, the artwork of the `audio_set` will never be required unless you are watching at the `audio_set` directly.
```sql
-- Audio with thumbnail & audio set
SELECT COUNT(id) FROM audio
WHERE thumbnail IS NOT NULL AND audio_set_foreign_identifier IS NOT NULL;
+-------+
| count |
|-------|
| 0     | …
```
> Make thumbnail link null for audio files without artwork

- api/catalog/api/views/media_views.py
Fixes #695 by @AetherUnbound 
This PR prevents thumbnail errors from causing server crashes by
- increasing timeout to 10s
- catching more known exceptions
- catching all unknown exceptions
0. Check out the PR and run the dev server.
1. Try generating thumbnails for many many images.
2. You should not encounter any uncaught exceptions.
<details>
```
Version 1.1
Suite D4700 …
```
> Prevent thumbnail timeout

- api/catalog/api/serializers/audio_serializers.py
- api/test/audio_integration_test.py
Fixes WordPress/openverse-frontend#1475 by @krysal
As the title says, omit the thumbnail links for those audio files without a cover.
You can try querying to find audio without a thumbnail and then make the request to confirm the link is not present in the response.
```sql
-- Pick an identifier from these results
SELECT identifier FROM audio WHERE thumbnail IS NULL;
```
```sh
curl http://localhost:8000/v1/audio/<identifier>
```
You can also run both project, the API and the frontend, and confirm it does show the default og image.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
```
> Make thumbnail link null for in audio detail endpoint when it doesn't exist

- api/catalog/api/views/media_views.py
- api/test/api_live_integration.py
Related to #729 by @AetherUnbound 
This PR uses @krysal 's [suggestion](https://github.com/WordPress/openverse-api/issues/729#issuecomment-1163336180) to add an IndexError handling for when there are no `hits` in the search controller:
https://github.com/WordPress/openverse-api/blob/7414174a16ba4cbd6af70773ce6d19b92b0e96de/api/catalog/api/controllers/search_controller.py#L344
On main, if you go to `http://localhost:8000/v1/images/000000000000000000000000000000000000/related/`, you would get a 500 error.
On this branch, you should get a 404.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Fix invalid UUID breaking related images query

- api/catalog/api/serializers/media_serializers.py
- api/test/audio_integration_test.py
- api/test/image_integration_test.py
- api/test/media_integration.py
Fixes #740  by @obulat 
This PR fixes the issue of the case sensitivity of the license filter. It only required a tiny change in the serialzier.  
on main, Both endpoints `http://localhost:8000/v1/images?license=cC0,By` and `http://localhost:8000/v1/images?license=cc0,by` returns the same output
<details>
```
Version 1.1
Suite D4700
By …
```
> License validation does not work correctly for non-lower-case strings #740

- api/Pipfile
- api/Pipfile.lock
- api/catalog/logger.py
- api/catalog/settings.py
Part of #775  by @sarayourfriend 
Adds request IDs to all logs so that we can trace them easily throughout a request without having to rebuild it ourselves (we can simply query for the request ID and then follow a request's logs in their entirety).
I want to split out this part from https://github.com/WordPress/openverse-api/pull/776 because it applies cleanly without interrupting the revert of https://github.com/WordPress/openverse-api/pull/741 that @dhruvkb is going to work on. Getting request IDs so that we can trace logs through requests is useful at any point that we deploy next, even if we don't get in new diagnostic logging.
Initially I was going to write the filter and middleware myself but [this library](https://github.com/dabapps/django-log-request-id) appears well enough …
> Add request id to logs

- api/catalog/api/controllers/elasticsearch/search.py
Fixes #728 by @AetherUnbound 
We were getting 500 errors when attempting to filter by mature content: http://localhost:8000/v1/images/?mature=true
The problem is caused by [this line](https://github.com/WordPress/openverse-api/blob/main/api/catalog/api/controllers/elasticsearch/search.py#L154), which attempts to append the `rank_queries` to the query we've built so far:
```
s.query = Q("bool", must=s.query, should=rank_queries)
```
The problem is that when we filter by `mature=true` and _no other filters_, no query has been built[^1]. That's because we don't actually add a Query when `mature=true` is passed as a query param (ie we treat this as "return mature results _as well_ ", rather than "return _only_ mature results"). 
* For this reason, you can actually filter by `mature=true` as …
> Fix search when no filters are applied

- api/catalog/management/commands/resendoauthverification.py
- api/test/unit/management/commands/resendoauthverification_test.py
Fixes #770 by @zackkrida 
Corrects the email. I took a shot at the text of the corrected email but please feel free to offer better wording if you can think of any!
Follow instructions from the original PR for testing locally: https://github.com/WordPress/openverse-api/pull/694
Note also that CI should pass.
> Add back and correct "resendoauthverification" command

- api/catalog/api/views/oauth2_views.py
- api/test/auth_test.py
The `/v1/rate_limit/` endpoint was missing the ability to handle the `exempt` rate limit model added in #792.
I added the handling for the exempt rate limit model into the view and also updated the unit tests so that they automatically test all the available rate limit models. This will prevent future additional rate limit models from having the same problem.
Check out the unit tests. Also make the request yourself if you want to.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```
> Fix missing rate limit model from rate_limit info endpoint

- .github/workflows/ci_cd.yml
Fixes #817  by @sarayourfriend 
Applies the same fixes and strategies from https://github.com/WordPress/openverse-frontend/pull/1574 to the API so that we stop keeping a useless history of the `gh-pages` branch.
Checkout the preview and make sure it works.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Use force_orphan to prevent gh-pages branch history from ballooning repo size

- .github/workflows/ci_cd.yml
Fixes an issue @zackkrida noticed.
Merge and see if it works
<details>
```
Version 1.1
Suite D4700
By making a …
```
> Use sudo when removing preview folders

- api/catalog/settings.py
Ignores the logging mentioned in the comment as it's completely un-actionable.
Run the API locally and verify that you can make requests without issue.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Ignore DisallowedHosts logs from Sentry

- api/Pipfile
- api/Pipfile.lock
- api/catalog/api/controllers/search_controller.py
- api/catalog/api/utils/pagination.py
- api/test/dead_link_filter_test.py
- api/test/unit/controllers/test_search_controller.py
Fixes #857 by @zackkrida
This PR adds a cap to the number of pages returned in API results to 20 (defined by `MAX_TOTAL_PAGE_COUNT` in `pagination.py`). It does so by:
1. Preventing the pagination class from setting a page size that's higher (e.g. when `page` is in the query parameters)
2. Limiting the number returned when determining "result and page count"
The former is pretty straightforward and I've added tests for that case. The latter makes way less sense to me. I've capped the `page_count` within that function to `MAX_TOTAL_PAGE_COUNT` as well, but the logic within it is confusing. I wrote tests along with it with some of my own notes. I hesitate to change _more_ functionality because the current calculations are "working", I only altered what the possible cap was.
- `just …
> Limit page depth of searches

- justfile
- load_sample_data.sh
Fixes #828 by @dhruvkb (without the conversion to Python)
This PR fixes a syntax error caused by a missing space after `[`.
0. Run `just init`.
1. Observe that image ingestion runs once.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```
> Fix syntax error in sample data load script

- api/catalog/api/controllers/search_controller.py
- api/catalog/api/utils/validate_images.py
- api/test/dead_link_filter_test.py
Fixes #855 by @sarayourfriend
If after validating dead links, there are zero results, assume any subsequent deeper paginations of the same query will not yield better returns. The lines changed is a lie: it's like 97% changes in the unit tests. The actual change required to make this work is two SLOC with some explanatory comments.
Check out the unit tests. To test this locally the best thing to do would be to use OpenSnitch or some other firewall to block outbound requests to Flickr. Then observe the logs and ensure that only a single query is sent to Elasticsearch. Note: this will be hard to do if on Linux with Docker as root (you'll need to mess with a bunch of iptables configurations). Instead, you can just modify the code to set the status code on the responses manually using this …
> Only backfill dead links if at least one on first page was not dead

- api/catalog/api/utils/validate_images.py
Fixes #867 by @obulat 
Makes the link validation cache expiration times minimally configurable and increases the valid link cache time to 30 days.
I have another patch that introduces more flexible configuration by status code, in case that is something we want to explore.
Checkout this branch and `just down && just up` to ensure you get the latest code. Smoke test the app around link validation and confirm that things are getting cached. You can do so by observing the log output. For example, a request to `/v1/images/` will output a bunch of warning logs about making insecure requests to staticflickr the first time but should not output any on the second request.
If you want to confirm the cache times more explicitly, you'll need to upgrade redis locally to version 7 so that you can use …
> Extend valid link cache time to 30 days and make cache expiration times minimally configurable

- api/catalog/api/utils/throttle.py
- api/catalog/api/views/image_views.py
- api/catalog/settings.py
Fixes #863 by @zackkrida
As title says, adds the `AnonThumbnailRateThrottle` and `OAuth2IdThumbnailRateThrottle` classes.
1. Set the following variables in your `end.docker` file
```
DISABLE_GLOBAL_THROTTLING=False
THROTTLE_ANON_THUMBS=2/minute
```
2. `just up`
3. Try viewing 3 thumbnails (or just one refreshing more than twice)
4. You should get throttled in this endpoint
5. Repeat for the authenticated (**verified**) version 
<details>
```
Version 1.1
Copyright (C) …
```
> Add throttling classes for thumbnail endpoint

- api/test/audio_integration_test.py
- api/test/factory/faker.py
- api/test/factory/models/media.py
Fixes #883 by @sarayourfriend 
Related to #866 by @sarayourfriend
It turns out the issue with the flaky tests is two fold. We do indeed have the chance for a run to have non-unique urls that clash with database constraints. That is fixed in this PR through adding a new Faker provider `globally_unique_url` that appends a UUID to the URL that Faker uses. Faker's approach does include randomness but it has a small search space, so clashes are easy to come by (especially when generating hundreds of fixtures like we do in some of our tests):
```py
def url(self, schemes: Optional[List[str]] = None) -> str:
"""
:param schemes: a list of strings to use as schemes, one will chosen randomly.
If None, it will generate http and https urls.
Passing an empty list will result in schemeless url …
```
> Prevent tests from making network requests for link validation and fix potentially non-unique factory props

- api/catalog/api/views/media_views.py
- api/test/factory/models/image.py
- api/test/image_integration_test.py
- api/test/unit/views/media_views_test.py
Fixes #847 by @sarayourfriend 
Fixes the issue by returning a 424: https://httpstatus.in/424/
> The method could not be performed on the resource because the requested action depended on another action and that action failed.
This makes sense for this error because we're not encountering a problem ourselves, rather there is an issue with the dependency (the upstream provider).
Still capture the exception in Sentry so that it can be addressed and tracked.
Checkout this branch and `just down && just up` to get the fresh code running. Block a request to a provider using a firewall and see that 424 is returned. 
Check out the unit test. I tried to add it to the existing media integration suite but that wasn't possible because it didn't allow for mocking the `urlopen` function as that whole …
> Do not 500 when upstream provider is unavailable

- .github/workflows/ci_cd.yml
- api/README.md
- api/catalog/settings.py
- api/docs/guides/quickstart.md
- api/docs/guides/test.md
- api/run.sh
- docker-compose.yml
- ingestion_server/test/gen_integration_compose.py
- ingestion_server/test/test_constants.py
- justfile
- nginx/templates/web.conf.template
Addresses WordPress/openverse#200
This PR
- removes binding for ports that are only used for internal communication
- changes port mappings to ports in the 502xx range to prevent any conflicts with services running on the host
- updates documentation and tests to keep up with the changes
- fixes some small side issues along the way
- removing unused settings
- using env vars in the `run.sh` entrypoint code and aligning it with the `justfile`
- using the `_api-up` recipe in more places
- converting the NGINX conf into [a template to use env vars](https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119)
0. Check out the PR and run the dev server.
1. Visit some endpoints that can help gauge the communication between processes …
> Remap ports to the non-conflicting range

- api/docs/guides/quickstart.md
- justfile
Fixes https://github.com/WordPress/openverse-api/pull/862#discussion_r947863430 by @dhruvkb 
Add a `dc` recipe to make running docker-compose with the correct environment easy. This also cleans up repeated stuff from our justfile.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Add `just dc` recipe

- .github/CODEOWNERS
Updates the CODEOWNERS file to use the new [dedicated API Team](https://github.com/orgs/WordPress/teams/openverse-api).
> Update CODEOWNERS to use new API team

- api/catalog/api/controllers/search_controller.py
- api/catalog/api/utils/validate_images.py
Developed in collaboration with @stacimc @obulat and @AetherUnbound.
Read the comments. We can try to further clarify things if necessary.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
> Add comments to pagination and dead link mask and validation

- api/catalog/api/controllers/search_controller.py
- api/test/unit/controllers/test_search_controller.py
Fixes #871 by @AetherUnbound
Wow, what a monster of a function. There are a lot of branches, each with their own possible edge cases. The third branch is by far the most complex and writing cases for it is likewise complex. I've had a hard time wrapping my head around possible edge cases, particularly because the third branch handles the edge cases so well, so each sub-branch is already exercising one possible edge case anyway. I think they're all sufficiently covered, but let me know if you notice any holes.
Read the tests. They should pass CI and should make sense. Review the additional documentation I've added.
<details>
``` …
```
> Add unit tests for _paginate_with_dead_link_mask

- api/catalog/api/utils/validate_images.py
- api/catalog/configuration/link_validation_cache.py
- api/catalog/settings.py
- api/test/unit/configuration/link_validation_cache_test.py
Fixes #878 by @obulat 
An alternative version of my [other PR to address this issue](https://github.com/WordPress/openverse-api/pull/878) that introduces maximal configurability into the cache times so that we can tweak times for any status code without having to make new releases.
Follow the test instructions in https://github.com/WordPress/openverse-api/pull/878. They are the same here, however in this PR you should also test adding a new environment variable for a status that is not included in the list of default statuses and confirming that it has the expiration used for it.
Also check out the unit tests for the configuration class and confirm they are sufficiently comprehensive.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelin …
> Make link validation expiry maximally configurable

- api/catalog/api/controllers/search_controller.py
#698 by @dhruvkb 
Sends the query arguments as an array. All credit goes to @sarayourfriend  and @obulat for their code on #764 pr. I tested it out on POSTMAN and it works perfectly. 
As you can see, the server recieves query parameters as an array
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
> Uses a terms array to query data

- api/catalog/api/views/image_views.py
- api/test/image_integration_test.py
Fixes #927 by @AetherUnbound 
Addresses #925 by @chrisbartoloburlo
This PR fixes the issue of `AssertionError`s being raised instead of a 404 response. The docs for `get_api_exception` say that they are supposed to be used with the `raise` keyword as what it returns are exceptions, not responses.
This PR also handles trailing slashes in URLs. We have been consistently pushes for uniformly using trailing URLs everywhere so our own endpoints should reasonably support them. This is a backwards compatible change.
This PR also adds tests for these changes so that we never regress on them in the future.
<details>
```
Developer …
```
> Make improvements to the oEmbed endpoint

- .github/dependabot.yml
Small PR to correct a comment around the frequency of dependabot upgrades.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
> Correct schedule interval comment in dependabot config

- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/slack.py
- justfile
Fixes #887 by @AetherUnbound
This PR builds off of the changes in #707 and corrects some of the messaging around next steps within the data refresh update steps.
I've also added a new `slack::status` method which will prepend the model name to the beginning of the slack message, which should hopefully make it easier to be more consistent around the messaging. Admittedly "status" is a pretty generic name, if folks think `data_refresh_status` or something else would be better, happy to rename it! 
I've added a just recipe for the index deletion step too, which is in-line with the other recipes we have around indexing.
The best way to run this would be to add a `SLACK_WEBHOOK` URL to the `ingestion_server/env.docker` file, then run the following:
1. `just recreate` - this will run the audio …
> Correct data refresh status message next steps

- .pre-commit-config.yaml
- api/test/run_test.sh
- ingestion_server/test/run_test.sh
- ingestion_server/test/update_mocks.sh
- load_sample_data.sh
Adding shell check to openverse-api repo
> Adding shellcheck to openverse-api

- api/catalog/api/utils/watermark.py
- api/env.docker
- api/test/unit/utils/watermark_test.py
Fixes #849 by @sarayourfriend 
This PR:
- catches struct errors from `piexif.load` function. The last release of this library is from July 2019, so it will need a replacement sooner than later
- sets environment variables to enable the watermark endpoint locally and name the environment properly
I was writing a test but it wasn't failing even before the fix and it's taking too much time to mock. I haven't found a way to reproduce the error locally so hoping just to catch the exception to solve the Sentry alerts.
<details>
<summary>Non failing test</summary>
```python 
import struct
from io import BytesIO
from PIL import Image
from unittest import mock
from catalog.api.utils.watermark import _open_image
...
def test_catch_struct_errors_from_piexif(requests):
with …
```
> Catch struct errors in `watermark/` endpoint

- .github/workflows/actionlint.yml
- .github/workflows/build_imaginary.yml
- .github/workflows/ci_cd.yml
- .github/workflows/migration_safety_warning.yml
- .github/workflows/push_docker_image.yml
Related to [openverse #267](https://github.com/WordPress/openverse/issues/267#issue-1288144556) by @sarayourfriend 
This pull request Adds concurrency settings for workflow
<details>
```
Version 1.1
Suite D4700
have …
```
> Add concurrency settings for workflow

- justfile
This PR allows passing more than one argument to the recipe `up`, thereby enabling commands like the following:
```
$ just up --force-recreate web
```
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
> Allow more than one argument to recipe `up`

- api/catalog/api/docs/README.md
- api/catalog/api/models/models.py
- api/catalog/urls/__init__.py
Prevents confusing errors like [this reported in the Fixing WordPress Forums](https://wordpress.org/support/topic/openverse-register-error/). The user was trying to register for a key following instructions but the API returned the following:
```json
{
"detail": "Method \"GET\" not allowed."
}
```
I tried to reproduce it and found this happens when missing the trailing slash in the endpoint.
This PR fixes the docs URLs to prevent this from happening. Also includes some other minor docs changes to remove warnings when building sphinx docs (`just sphinx-make`).
`just up` and check http://localhost:50280/v1/#section/Register-and-Authenticate
<details>
<summary>Developer Certificate of …
> Fix URL in API consumer docs

- .gitignore
- DOCUMENTATION_GUIDELINES.md
Fixes #992 by @yash-pratapwar
This PR adds the link for automaed tests files in [DOCUMENTATION_GUIDELINES.md](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#documentation-guidelines)
Go to [DOCUMENTATION_GUIDELINES.md](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#documentation-guidelines)
Navigate to [How to Start Contributing](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#how-to-start-contributing)
Click on the [link](https://github.com/WordPress/openverse-api/blob/main/.github/workflows/integration-tests.yml) in the 3rd point under [How to Start Contributing](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#how-to-start-contributing)
See the fix. …
> Added link for automated tests files in DOCUMENTATION_GUIDELINES.md

- api/Dockerfile
- api/nginx.conf.template
- justfile
This is necessary for continued work on https://github.com/WordPress/openverse-infrastructure/issues/175
This PR makes a few changes to the nginx target image for the API in order to prevent the need for mounting any files into the docker container. Previously, the `/version` was configured to return the contents of a `version.json` file. This file was created during deployment and mounted into the nginx image:
https://github.com/WordPress/openverse-infrastructure/blob/369d7858636797de276dbfc299b90b822a5ac527/modules/services/openverse-api/init.tpl#L79-L85
The issue with this is that we are trying to avoid the need for mounting anything into our API-related containers. This was the last necessary item that was being mounted. You can see that this endpoint is not served by the API by …
> Allow `/version` to be defined by environment variables

- api/catalog/api/controllers/search_controller.py
- api/catalog/api/examples/audio_requests.py
- api/catalog/api/examples/image_requests.py
- api/test/audio_integration_test.py
- api/test/image_integration_test.py
- api/test/media_integration.py
Fixes #933 by @AetherUnbound 
Conditionally applies the `quote_field_suffix` query feature as suggested in the Elasticsearch documentation that @AetherUnbound shared in the linked issue: https://www.elastic.co/guide/en/elasticsearch/reference/current/mixing-exact-search-with-stemming.html
We can continue to "boost" exact matches against the title as we originally were, but I've added the `.exact` modifier there as well to ensure that the boost only applies to actual exact matches.
The latter is hard to test locally, I haven't found any suitable queries for it in the test data and I do not know how to efficiently add usable test data.
The former, however, is pretty straightforward to test locally. Find a query that returns some results that you could narrow using an exact match. I found …
> Make quoted queries behave as described in the API documentation (return exact matches only)

- api/catalog/api/utils/validate_images.py
- api/test/unit/utils/validate_images_test.py
Fixes https://sentry.io/share/issue/bc0a4a1acfba45b6a8daca58a8e39ef2/ (which originated from #1027)
Handles the TimeoutError when it is raised as it is not part of ClientError.
We tested the timeout configuration in ipython manually to confirm that it works in actual network scenarios:
```
In [3]: import aiohttp
In [4]: timeout = aiohttp.ClientTimeout(total=2)
In [5]: async with aiohttp.ClientSession(timeout=timeout) as session:
...:     await session.get("https://httpbin.org/delay/3")
...: 
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In[5], line 2
1 async with aiohttp.ClientSession(timeout=timeout) as session:
----> 2     await session.get("https://httpbin.org/delay/3")
File …
```
> Handle `asyncio.TimeoutError` for link validation code

- .github/workflows/ci_cd.yml
- api/Dockerfile
- api/Pipfile
- api/Pipfile.lock
- docker-compose.yml
- justfile
Related to #952 by @zackkrida in the sense that, if I remember correctly, it was driven by a difficulty presented to @stacimc to connect to the API DB.
This PR:
- installs `pgcli` as dev dependency
- adds a `just dbshell` _and_ `just pgcli` commands, taking inspiration from [the one in the catalog repository](https://github.com/WordPress/openverse-catalog/blob/main/justfile#L115-L117) and using the provided[ django command](https://docs.djangoproject.com/en/4.1/ref/django-admin/#dbshell) as well
- adds a non-root `opener` user to the `web` container, removing the tricky pass of the host user, it wasn't working well in macOS, so I believe creating a proper user is the best route we can follow
- adds `GITHUB_TOKEN` to steps so setup just, it's necessary to prevent rate limiting errors (as …
> Add db connection commands and non-root user for `web` container

- api/Pipfile.lock
Fixes #1058 by @AetherUnbound 
This PR adds the hash for the wheel distribution of `livereload` to resume installations using Pipenv. Refer to the issue for [further details](https://github.com/WordPress/openverse-api/issues/1058#issuecomment-1364662958) on why this broke.
0. Check out the branch.
1. Try building the `web` container: `just dc build web`.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
> Add hash for `livereload` wheel

- CONTRIBUTORS.md
- api/docs/guides/quickstart.md
Fixes #1061
Added `coreutils`  to the pre-reqs and a small description.
errors.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
> Added coreutils to the pre-requisites

- api/catalog/api/views/health_views.py
- api/test/unit/conftest.py
- api/test/unit/views/health_views_test.py
- api/test/unit/views/image_views_test.py
- api/test/unit/views/media_views_test.py
Fixes #14 by @obulat 
Adds Elasticsearch status checks to the `/healthcheck/` endpoint when `check_es` is in the query params.
Note: I chose not to implement a serializer for the query params to avoid over-complicating the implementation of what is an otherwise very straightforward request to process. If this does happen to get more complex in the future, like if we add different `check_*` params, a serializer might then become appropriate.
I'm leaving this as a draft to allow discussion in the issue to decide whether this approach actually makes sense for our usage of the healthcheck endpoint.
Check out the unit tests and confirm they make sense. There's not _really_ a good way to test this practically as far as I can tell unless you do something to brick your local ES cluster. I'm not …
> Add ES healthchecks to `/healthcheck/` endpoint

- api/catalog/api/utils/photon.py
- api/test/unit/utils/photon_test.py
Some providers do not serve results over HTTP and do not redirect. The only known case of this is WP Photo Directory. We need to send an `ssl=true` query parameter to Photon for it to make the upstream request using HTTPS when the image URL we have is HTTPS.
Send `ssl=true` when image_url scheme is HTTPS.
Check unit tests and confirm they correctly test the fix.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Forward SSL status of upstream image URL to Photon

- api/catalog/api/controllers/search_controller.py
- api/catalog/api/utils/tallies.py
- api/test/unit/controllers/test_search_controller.py
Staci and I noticed two issues while we were deploying the API today:
1. If the page_size changes (for example to 200), then if we tally the first 4 pages, we'd be tallying the top 800 results, which does not really reflect the intention of the tallying (for seeing the provider density of "top results"
2. On weeks that include a month boundary, the "monday" date stamp calculation was incorrect. We only found this because we were working on this literally as 00:00 UTC 1 Feb 2023 rolled over from January!
Applies fixes for the above described issues. There are (hopefully) sufficient comments to hopefully describe the approach and intentions as the logic is a bit convoluted.
Check out the much expanded unit tests. You can test locally following the process Staci describes here: …
> Tally top 80 results exactly and fix "monday" timestamp calculation

- api/catalog/api/controllers/search_controller.py
- api/test/unit/controllers/test_search_controller.py
Fixes #1131 by @AetherUnbound
This PR initializes `results_to_tally` to either `results` or `[]` so that any operations on it which assume it's a list will behave correctly.
1. Check out commit 65f2df5b8540eaae4ae2d7a40474620f3b5e5c72 and run `just api-test` - tests should fail and emulate current behavior
1. Check out the tip of this branch and run `just api-test` - tests should now pass!
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> Handle tally cases where `results` is `None`

- .github/workflows/ci_cd.yml
- api/Dockerfile
- docker-compose.yml
Fixes https://github.com/WordPress/openverse-infrastructure/issues/332 by @AetherUnbound
This PR changes the API and API nginx images to include the image tag as a part of the built docker images, so it can be referenced appropriately once the service is deployed without having to alter the ECS task definition every time.
The logic I've added _should_ use the github SHA as the `SEMANTIC_VERSION` for all pushes to main, but use the ref name (e.g. tag version like "v2.5.10") for all releases.
Very hard to test GitHub actions, this is based off of similar work on the frontend so I'm hoping it works!
errors.
<details>
<summary>Developer …
> Include image tag in built image
