WordPress/openverse-api

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Addresses WordPress/openverse#20.
This PR adds a workflow and associated configuration for Release Drafter.
> Add configuration and workflow for Release Drafter

- .github/workflows/integration-tests.yml
- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/cleanup.py
- ingestion_server/ingestion_server/indexer.py
- load_sample_data.sh
- openverse-api/catalog/api/serializers/link_serializers.py
Fixes #122.
Addresses WordPress/openverse#32.
This PR restores tests that will run
- for every push to `main`
- for every PR
- on demand
It also fixes violations that cause the code style tests to fail.
> Restore tests and fix causes of failure

- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/distributed_reindex_scheduler.py
- ingestion_server/ingestion_server/indexer_worker.py
This PR updates the import paths for the media type constants defined in PR #116.
> Update import path for media types

- .github/PULL_REQUEST_TEMPLATE.md
Targets WordPress/openverse#35
This PR adds a PR template to the repository.
> Add a PR template to the repository

- load_sample_data.sh
- openverse-api/catalog/api/controllers/search_controller.py
Signed-off-by: Olga Bulat <obulat@gmail.com>## Fixes
Fixes #161 
This PR makes required changes to the new audio data to make the CI tests pass.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```
> Fix array fields in audio data

- load_sample_data.sh
- openverse-api/catalog/api/controllers/search_controller.py
Signed-off-by: Olga Bulat <obulat@gmail.com>
This PR adds a new `sample_audio_data.csv` with 5000 items for better prototyping and search testing.
The file is created using one source, Jamendo Music.
I tried testing audio endpoints, and the search results usually have no more than 1-2 results because currently we only have 100 items in the sample audio data.
<details>
```
Version 1.1
Suite D4700
license document, but …
```
> Add new sample data for audio

- load_sample_data.sh
This PR updates the `load_sample_data.sh` script to add the correct content providers as per the new sample data for audio and images.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
> Update content providers to match the new sample data

- openverse-api/catalog/settings.py
- openverse-api/catalog/templates/drf-yasg/redoc.html
- openverse-api/catalog/urls.py
This PR
- adds the Openverse logo in the Redoc docs sidebar
- updates references to CC in the text
- adds the Openverse icon as the favicon
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
> Add the logo and make small text fixes in the API docs

- .gitattributes
Fixes WordPress/openverse#49
This PR marks files with a `.PNG` extension as binary so that they are not subjected to LF/CRLF line ending rules after being cloned.
File systems like Linux are case-sensitive so they don't match the existing `*.png` rule to the `*.PNG` files present in the repo.
<details>
```
Version 1.1
Suite D4700
By …
```
> Add uppercase extension for case-sensitive file systems

- openverse-api/test/media_integration.py
Fixes typo introduced in #160 
Fixes incorrect description caused by inattentiveness during copy-pasting.
<details>
```
Version 1.1
Suite D4700
indicated in …
```
> Update description in base media API test cases

- openverse-api/catalog/api/controllers/search_controller.py
Page count was off by one in some cases. Add a condition to check if
results is divisible by page_size. If not, increment page_count by 1.
<s>Fixes</s> #196 by @dhruvkb
Fixes #172 by @dhruvkb
Adds a check in result count calculation. If result_count is not completely divisible by page_size, increment page_count by one.  
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Update page_count calculation to fix off-by-one issue

- README.md
Adds additional previous contributors to CC Search
Fixes WordPress/openverse#53
<details>
```
Version 1.1
Suite D4700
(b) The …
```
> Update acknowledgements section

- .github/dependabot.yml
The label check are failing on Dependabot PRs due to inadequate labelling. This PR fixes that.
It also configures Dependabot to check the ingestion-server for updates.
<details>
```
Version 1.1
Suite D4700
have the …
```
> Add Dependabot for ingestion API

- openverse-api/catalog/api/models/__init__.py
Fixes #232 by @krysal
Fix the project startup by moving the import of `catalog.api.models.base.OpenLedgerModel`.
Adds `# isort:skip` at the end of the import so this line is not moved by the pre-commit hook.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
> Fix circular import of OpenLedgerModel

- justfile
- load_sample_data.sh
- openverse_api/catalog/api/examples/audio_requests.py
- openverse_api/catalog/api/examples/audio_responses.py
- openverse_api/test/examples_test.py
This PR
- makes fixes/improvements to sample data
- replaces `wikimedia` with `wikimedia_audio` to classify it as a different provider  
WordPress/openverse-catalog#219
- removes incorrect value `""` for array fields replacing them with `null` instead  
WordPress/openverse-catalog#220
- updates tests to make CI pass
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Make corrections to sample data and tests to restore CI

- .github/dependabot.yml
This PR adds the default priority labels for PRs made by Dependabot.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
> Add priority labels to Dependabot PRs

- openverse_api/Pipfile
- openverse_api/Pipfile.lock
We are experiencing a number of issues with uWSGI in production for the API server. All of our other services use `gunicorn`, so it seems fitting to have the API use it too.
<details>
```
Version 1.1
Suite D4700
have …
```
> Add gunicorn to project requirements

- docker-compose.yml
Fixes #407 by @AetherUnbound
This PR adds docker volumes for both DBs and ES.
1. `just init`
1. `just down`
1. `just up` - databases should be migrated and indices should still exist in ES
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```
> Add docker volumes for local development

- ingestion_server/Dockerfile
Fixes #413 by @AetherUnbound
This PR updates the `TLDEXTRACT_CACHE` environment variable to a writable directory (`/tmp`) so caching can succeed. The default directory ([described here](https://github.com/john-kurkowski/tldextract)) is not writable (and this is easier than trying to determine why the `supervisord` user can't write to `/home/supervisord` :grimace: ).
Run the following: `docker-compose -f docker-compose.yml run --rm --no-deps ingestion_server python -c "import tldextract; tldextract.extract('https://github.com/WordPress/openverse-api/issues/413')"`
The above command will give a warning when run on 075cf45bbb4c13b3b24734f88c5c7832c7e9e10e, but should produce no output when run on this branch.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Pr …
> Set tldextract cache to writable directory

- .github/dependabot.yml
- .github/release-drafter.yml
- .github/workflows/integration_tests.yml
- .github/workflows/new_issues.yml
- .github/workflows/new_prs.yml
- .github/workflows/pr_label_check.yml
- .github/workflows/pr_ping.yml
- .pre-commit-config.yaml
- analytics/docs/swagger.yaml
- docker-compose.yml
- ingestion_server/docker-compose.yml
Fixes #410 by @dhruvkb
This PR adds a new `pre-commit` hook to format YAML files.
Formatting changes are adequately tested by passing lint check.
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
> Add hook to clean up YAML files

- .github/dependabot.yml
This PR
- removes Dependabot from the Docker images as they are normally pinned to the semver minor version
- reduces the frequency of Dependabot from weekly to monthly to control the deluge of PRs
This seems to be the consensus in the dev team.
This is hard to test locally. We can just double-check the code against the [Dependabot configuration docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates).
<details>
```
Version 1.1
1 …
```
> Remove Dependabot for Docker and reduce frequency

- ingestion_server/publish_release.sh
Fixes #441 by @dhruvkb 
Deleted the file **publish_release.sh** and checked if any references exist to the same
<details>
```
Version 1.1
Suite D4700 …
```
> Deleted all instances of publish_release.sh

- .github/dependabot.yml
The Dependabot config sets Dependabot to use the "python" label on its PR, which no longer exists. This PR updates the label to the new `tech:` format.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
> Update the Python label that Dependabot uses

- ingestion_server/ingestion_server/tasks.py
This PR changes the formatting of exception message slack alerts so that the entire exception body appears in preformatted text. It also adds an alert at the start of one-off reindex tasks.
1. Perform a reindex locally
1. Check that the message function has called (it will produce a `DEBUG` log to show it has been called).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Improve ingestion server slack alerts

- .github/workflows/ci_cd.yml
- justfile
This PR adds the steps to deploy Sphinx docs to GitHub pages to the CI + CD workflow.
0. Visit the Actions page for a successful workflow run.
1. Download the `docs` artifact to confirm that it is a valid HTML directory (containing `index.html`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
> Update CI + CD pipeline to deploy Sphinx docs to GH pages

- .github/workflows/ci_cd.yml
Follow up to #469 that updates some other references.
Hoping this will be the last change :see_no_evil:
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
> Push tags with `openverse-` prefix

- README.md
Fixes #488 by @AetherUnbound
This PR adds a reference to our quickstart and API documentation in the REAMDE.md. The API documentation is actually referenced later in the file as well, but I don't think having it in both locations hurts. I know for myself the quickstart is what I typically go to when I'm interested in contributing, so I wanted to have that be close to the top of the README. I'm open to thoughts on whether it belongs elsewhere though :slightly_smiling_face:
<details>
```
Version 1.1
Suite D4700
San …
```
> Add quickstart and API documentation to README.md

- api/catalog/api/serializers/audio_serializers.py
Fixes #526 by @obulat
Related to WordPress/openverse-catalog#402
This PR adds `pronunciation` as a valid category for audio records.
The serializers currently do not have any tests associated with them. I could add some unit tests to this PR, but I know this is high priority work and the unit tests would ideally be fairly expansive. I'd prefer to make a separate ticket for serializer unit tests, but I'm open if folks don't think this should go through without tests.
Alternatively, you can test this locally with the following URLs:
- Passes: http://localhost:8000/v1/audio/?q=cat&categories=pronunciation
- Fails: http://localhost:8000/v1/audio/?q=cat&categories=sound,pronunciation …
> Add pronunciation as valid sound category

- .pre-commit-config.yaml
- api/catalog/api/models/media.py
- api/catalog/api/models/mixins.py
This PR updates the version of Black used in pre-commit to the latest stable version. This also makes it consistent with the changes proposed in WordPress/openverse#201.
<details>
```
Version 1.1
Suite D4700
have the …
```
> Update Black version to latest stable

- api/catalog/api/utils/waveform.py
Fixes #575 by @obulat
This PR prevents waveform peaks from going below zero. This has also been handled in the frontend by PR WordPress/openverse-frontend#1148. But it's best to fix it at the source.
It's not necessary to test this PR.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Prevent negative values in waveform data

- api/catalog/settings.py
Fixes #582 by @AetherUnbound
This PR adds a fix for the CSRF issue we were seeing in development and production by adding a `CSRF_TRUSTED_ORIGINS` setting.
I was unable to replicate this issue locally (even with #574 in place), but I deployed this commit to staging and I was able to successfully login (whereas I previously got the CSRF error described in the ticket)!
Attempt to log into the Admin UI in staging
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
> Add CSRF trusted origins setting

- justfile
In #618 we missed a tiny detail in the `install` recipe.
`just install` should not fail on a missing recipe error now :slightly_smiling_face: 
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```
> Fix install script for no more analytics

- api/catalog/api/serializers/base.py
Fixes #573 by @okosk
Rectifies #576 by @dhruvkb
This PR fixes a silly bug in the old PR and resolves the reopened issue.
See #576 for instructions.
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
> Fix bug in the URL scheme rewrite

- DOCUMENTATION_GUIDELINES.md
- api/catalog/api/docs/audio_docs.py
- api/catalog/api/docs/image_docs.py
- api/catalog/api/docs/media_docs.py
- api/catalog/api/examples/audio_requests.py
- api/catalog/api/examples/audio_responses.py
- api/catalog/api/examples/image_requests.py
- api/catalog/api/examples/image_responses.py
- api/catalog/api/views/oauth2_views.py
- api/catalog/example_responses.py
- api/catalog/logger.py
- api/catalog/settings.py
- api/docs/conf.py
- api/test/examples_test.py
Fixes #635 by @dhruvkb
This PR
- removes `# noqa` comments where they did nothing
- narrow `# noqa` comments to the specific error they suppressed
- clean up code in places where `# noqa` could be avoided by solving the issue itself
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Prune and narrow `# noqa` comments

- .github/workflows/build_imaginary.yml
- docker-compose.yml
This PR tests the possibility of building a custom, up-to-date Docker image for `h2non/imaginary`.
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
> Add a workflow to build our custom image for imaginary

- ingestion_server/ingestion_server/api.py
Quick fix for an issue with tracking the progress of the data refresh. The `progress` needs to be a `Value`.
@AetherUnbound and I tested this manually in staging and verified:
* Error reporting
* Active/progress/error reporting at these steps:
* `active` is True while the task is running, but before the indexing workers start (`percent_completed` is 0)
* `active` is still True after the task completes but workers are running (`percent_completed` between 0 and 100)
* `active` is still True while the `go_live` runs after worker completion (`percent_completed` is 100)
* `active` becomes False when the `go_live` step completes
<details>
<summary>Developer Certificate of …
> Fix tracking of data refresh progress

- .github/workflows/ci_cd.yml
- .github/workflows/pr_closed.yml
It's the same idea as our storybook/tailwind configuration deployment previews in the frontend, but with the developer docs that are published from the API :grin: 
Check the PR comments and try the preview link.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
> Add developer docs preview deployments

- .github/workflows/ci_cd.yml
This PR addresses an issue inadvertently added in #679 wherein the docs preview would attempt to run during the CI/CD steps that occur on `main` after a branch is merged.
This PR prevents the docs preview step from running on `main`. [Example of referencing the `main` branch](https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts)
We'll have to merge to main to find out!
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Do not run docs preview action on main branch

- ingestion_server/ingestion_server/ingest.py
- ingestion_server/ingestion_server/tasks.py
- load_sample_data.sh
Going through the logs for failed ingestions, the logs stop at this point:
https://github.com/WordPress/openverse-api/blob/270b086095ba125fa26e04bf27dff3ab6994e025/ingestion_server/ingestion_server/ingest.py#L338
It's natural to assume something funky has to be happening at that stage. By reversing the order to ingest audio first, we can skip the cleanup step and proceed, thus hopefully revealing more about the nature of this flakiness.
Nothing to test here really. It's just the same steps in a different order.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> Reverse indexing order for audio and images

- load_sample_data.sh
Fixes #467
Fixes #[648] by @AetherUnbound 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
> Use `::` over `cast` in audioset_view

- api/catalog/api/examples/image_requests.py
- api/catalog/api/examples/image_responses.py
Fixes #742 by @AetherUnbound
Supersedes #743
This PR updates the example image and commands to use an image that passes the dead link mask.
Note that Stocksnap does not have as much information available in the search results as Flickr (although it does have that information in the detail view).
1. `just api-test`
1. `just ing-testlocal`
<details>
```
Version 1.1
Suite D4700 …
```
> Update example image to one that passes dead link filter

- api/catalog/api/serializers/media_serializers.py
- api/catalog/api/views/media_views.py
- api/test/auth_test.py
- api/test/dead_link_filter_test.py
Fixes #751 by @sarayourfriend 
Adds the restriction for list views.
Make authenticated and unauthenticated requests to try the new limit.
```sh
curl -s "http://localhost:8000/v1/images/?page_size=22"
```
You should get: `{
"detail": "Page size must be between 0 & 20 for unauthenticated requests."
}` and for
```sh
curl -H "Authorization: Bearer <access_token>" \
"http://localhost:8000/v1/images/?page_size=22"
```
you should get results normally.
<details>
```
Version 1.1
Suite D4700
Everyone …
```
> Limit  `page_size` to 20 for unauthenticated requests

- api/catalog/api/docs/README.md
- api/catalog/settings.py
Fixes #762 by @sarayourfriend
This PR reduces the throttle threshold for bursts from 60/min to 5/hour, and sustained from 5000/day to 100/day. I've also modified the anonymous throttle settings to enable throttle configuration via environment variables. This will let us tweak these values where necessary without having to cut and deploy a new version.
The intent behind this effort is to encourage those who would like to consume our API to set up an OAuth application with us.
`just api-test` should be sufficient, but you can also add the following to `api/env.docker`, start the stack, and observe that all queries are throttled:
```bash
THROTTLE_ANON_BURST="0/second"
DISABLE_GLOBAL_THROTTLING="False"
```
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Projec …
> Reduce throttling threshold, allow throttling config via env vars

- .github/workflows/ci_cd.yml
- .github/workflows/pr_closed.yml
Fixes #692 
Let's see if the actions are skipped on this PR from a fork!
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
> Update action "if" conditionals: check if the PR head belongs to the upstream repo

- api/catalog/settings.py
Fixes #773 by @aod-123
this changes the token expiry time to 12 hours from the default 10 hours. 
we can observe the change when we generate a new token. The new value of the "expires_in" is "43200" which equals 12 hours. 
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
> increased token expiry to 12 hours

- api/catalog/settings.py
- api/env.docker
- api/env.template
Fixes #798 by @sarayourfriend
Make the `ALLOWED_HOSTS` Django setting configurable via an environment variable.
Modify the variable in your **api/docker.env** file by adding a custom domain name, and confirm the changes appear in the `settings.ALLOWED_HOSTS` configuration when running the API.
```sh
just ipython
...
In [1]: from catalog import settings
In [2]: settings.ALLOWED_HOSTS
```
<details>
```
Version 1.1
Suite D4700 …
```
> Use envvar for ALLOWED_HOSTS

- README.md
Fixes #[277](https://github.com/WordPress/openverse/issues/277) by @[[krystal](https://github.com/krysal)]
Header with a banner image and some useful links (to the project board, the Make blog, Slack, etc.) added.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
> Unify header added

- api/catalog/api/views/oauth2_views.py
- api/catalog/urls/__init__.py
- api/catalog/urls/auth_tokens.py
- api/test/api_live_integration.py
- api/test/auth_test.py
This PR adds trailing slashes to two URLs that did not have those. This makes them more consistent with the rest of the URLs in the codebase and also makes it possible to call them from the frontend (which mandatorily suffixes a slash to API calls).
It will not affect any existing users as `APPEND_SLASH` setting should ideally redirect them to the right address.
0. Check out the branch and run the dev server `just up`.
1. Try visiting the changed URLs (with and without the slash).
2. Observe redirects when you visit the URL without the slash.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```
> Add trailing slashes to URL conf paths

- api/catalog/api/controllers/elasticsearch/related.py
- api/catalog/api/controllers/elasticsearch/search.py
- api/test/audio_integration_test.py
- api/test/image_integration_test.py
- api/test/media_integration.py
Fixes #807  by @AetherUnbound 
Hit is not serializable, so we need to dump it to a dict like we do in the `search` module.
https://github.com/WordPress/openverse-api/blob/ce335722fe24ab574b463e227b965eab85621d43/api/catalog/api/controllers/elasticsearch/search.py#L248-L259
I also added integration tests for this. You can revert the change in `related.py` and see that the tests do fail so they are correctly testing the endpoint.
Check that CI passes. Run `just api-test` locally. Try to reproduce the bug according to the linked issue and confirm you cannot.
<details>
``` …
```
> Fix related media endpoint

- api/catalog/api/docs/README.md
Fixes #759 by @AetherUnbound 
Change link of `contributing on Github` in API docs to point to our CONTRIBUTING.md file.
<details>
```
Version 1.1
Suite D4700 …
```
> Update contribution link in API docs to point to CONTRIBUTING.md

- .github/workflows/build_imaginary.yml
Fixes the skipping seen here: https://github.com/WordPress/openverse-api/runs/7520883236?check_suite_focus=true
I'm not sure why the condition I originally wrote didn't work. Maybe this change will fix it? :thinking: I wish there was a way to test dispatched actions from PRs adding them :cry: 
Merge and try it again.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Fix if condition for thumbnails build/deploy

- .github/workflows/ci_cd.yml
Fixes #[issue number] by @[issue author]
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
> TESTING IGNORE ME PLEASE

- ingestion_server/ingestion_server/api.py
- ingestion_server/ingestion_server/es_helpers.py
- ingestion_server/ingestion_server/indexer.py
- ingestion_server/ingestion_server/indexer_worker.py
- ingestion_server/ingestion_server/tasks.py
- ingestion_server/test/integration_test.py
This PR adds a new task type `DELETE_INDEX` useful to delete unused indices via the API.
1. Try deleting an index that is not associated with an alias. It should succeed.
2. Try deleting an index that is associated with an alias. It should fail.
3. Try deleting an index that is associated with an alias using `force_delete` set to `true`. It should succeed. 
<details>
```
Version 1.1
Suite D4700
license document, but …
```
> Add task for deleting indices

- justfile
Fixes #791  by @AetherUnbound 
Run `init` as last step of `just recreate`
1. Run `just recreate`
2. Observe that environment is initialized with `init` command.
<details>
```
Version 1.1
Suite D4700
have the right to …
```
> Run init as part of just recreate

- .pre-commit-config.yaml
Fixes #853  by @sarayourfriend 
Change the order of pre-commit hook scripts. Black runs before Flake8. This improves figuring out linting issues. 
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
> Run black before flake8 in pre-commit hook

- README.md
Fixes #881 by @ramadanomar
The handbook hyperlink under the banner leads you to a page that doesn't exist. I already created an issue on the openverse-catalog repo but it applies to all openverse repos. 
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
> Updates handbook broken link

- docker-compose.yml
- justfile
Fixes #820  by @sarayourfriend 
Configures user to be used to run container commands.
This will fix file permission issue. By default files created by Docker are owned by `root`. This creates problem when a dev tries to manipulate those files.
<details>
```
Version 1.1
Suite D4700 …
```
> Define user to be used to run container process

- api/catalog/api/examples/audio_responses.py
- api/catalog/api/serializers/audio_serializers.py
- api/catalog/api/views/media_views.py
- api/test/unit/serializers/audio_serializers_test.py
Fixes #917 by @krysal
Related to #557 by @AetherUnbound 
This PR adds the `peaks` query param to make the inclusion of waveform peaks optional. It defaults to `False` to avoid sending large amounts of data unnecessarily.
We originally talked about naming the param `waveform` but that is the field name of the waveform link in the response, so `peaks` turned out to be more appropiate.
To test manually follow these steps:
1. Change to this branch
2. Make a new `sample_data/sample_audio.csv` with just a few entries, I just copied the first ~30 or so of the original file
3. Run `just recreate`
4. Run `just dj generatewaveforms`
5. Try the API with the new query parameter
- http://localhost:50280/v1/audio/
- http://localhost:50280/v1/audio/?peaks=true
- http://localhost:50280/v1/audio/?peaks=0 …
> Add `peaks` query param for audio requests

- docker-compose.yml
- ingestion_server/Dockerfile
- load_sample_data.sh
Follow up on #820.
The fix on #862 probed to reduce the number of failed remove operations for the **Publish developer docs** job. Before we were getting errors for files under the `api/` folder, and currently the problem persists but only for files under the `ingestion_server` so I believe adding the same user to those containers should fix it.
Compare jobs before and after #820:
- https://github.com/WordPress/openverse-api/runs/7617116799?check_suite_focus=true
- https://github.com/WordPress/openverse-api/runs/7978840111?check_suite_focus=true
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```
> Pass user to ingestion-server and indexer_worker containers

- docker-compose.yml
This PR adds CORS headers to the ES container which allows us to use [Elasticvue](https://elasticvue.com/) to visualise the contents of Elasticsearch from the browser. Without these headers, installing the browser extension was needed, but with these headers you can simply use the web app hosted at https://app.elasticvue.com/.
0. Check out the PR and bring up all the containers.
1. Visit https://app.elasticvue.com/.
2. See all ES contents.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> Add CORS configuration to ES container

- api/README.md
Addresses an issue brought up in #901
This PR fixes the link to the dev API documentation so it points at the API rather than the frontend docs.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```
> Fix dev API link in README.md

- api/catalog/api/controllers/search_controller.py
Fixes #915 by @zackkrida 
Replace low-level "more-like-this" search query in `search_controller` by `MoreLikeThis` class offered by `elasticsearch-dsl` package which implements the same. This is a cleaner implementation.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
> Use MoreLikeThis ES class for similar search in seach controller

- api/catalog/api/utils/exceptions.py
- api/catalog/api/views/audio_views.py
- api/catalog/api/views/image_views.py
- api/catalog/api/views/media_views.py
…RF exceptions
Fixes #843 by @sarayourfriend 
In this PR I have done the following: -
- Replaced all usages of `get_api_exception` function with the appropriate built-in DRF exception from `rest_framework.exceptions`.
- Also, for any that are following the `try: queryset.get(); except Model.DoesNotExist: ...` pattern, replaced it with [get_object_or_404](https://github.com/django/django/blob/3b79dab19a2300a4884a3d81baa6c7c1f2dee059/django/shortcuts.py#L64).
- Removed the `get_api_exception` function.
- Code Cleanup.
- While testing I followed the [developer doc](https://wordpress.github.io/openverse-api/guides/test.html) and all the test cases passed successfully.
<details> …
> Removed get_api_exception and replaced it with appropriate built-in DRF Exceptions

- api/catalog/api/models/audio.py
- api/catalog/api/models/image.py
- api/catalog/api/models/media.py
- api/env.docker
- api/env.template
Fixes #935 by @dhruvkb
I used the media details page of the API instead of the "landing page" because you'll need the fronted project running to actually see the landing page, and due to the discrepancy between content in different environments. The test data we use locally is not present on production and vice-versa, so if the person wants to see the reported media, it only needs one more click on the `url` field.
1. `just up`
2. Report an image and/or audio
3. Check the link in the Django admin 
- http://localhost:50280/admin/api/imagereport/
- http://localhost:50280/admin/api/audioreport/
<details>
```
Developer Certificate of …
```
> Fix link to audio/image details page in Django admin 

- .github/workflows/push_docker_image.yml
This is a small follow up to #821 to add the `api-nginx` image to the list of options when running the docker image push on-demand action. I've also changed the symbol from the backtick to a quote, since the backtick does not render as expected in the UI:
N/A, already ran with this option successfully: https://github.com/WordPress/openverse-api/pkgs/container/openverse-api-nginx
<details>
```
Version 1.1
Suite D4700
license …
```
> Add `api-nginx` to options for docker image push action

- .github/workflows/ci_cd.yml
This PR fixes the CI that was broken due to permission errors, arising presumably from merging #1013. The good news is that #1013 also contains the solution, [supplying the `DC_USER` variable in the CI](https://github.com/WordPress/openverse-api/pull/1013/files#diff-c80d54cb778b5196ee7b73e152870cac313eed095f65886e3f15247cdc900d1aR494-R495).
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies …
```
> Fix permissions when building docs

- api/docs/reference/index.rst
- api/docs/reference/search_algorithm.md
Fixes #8 by @obulat
Adds a new page to the API documentation site that describes the search algorithm. Openverse does not really have a strong "algorithmic" approach to search at the moment, though the document scoring section covers popularity data usage which is the closest to an algorithmic approach we have at the moment. Otherwise, the document describes our text analysis approach and the two different types of querying available via the API.
Here is the page in the doc preview: https://wordpress.github.io/openverse-api/_preview/1050/reference/search_algorithm.html
Read the documentation. Cross-reference it with `search_controller.py` and `es_mapping.py` and ensure it is as accurate as possible. Please note areas where further clarification would be helpful. Feel free to make …
> Add Search Algorithm page to API docs

- LICENSE
This PR changes the LICENSE file to update the copyright holder. By making both this repo and the frontend (WordPress/openverse-frontend#2034) use the same license we
- make the licenses consistent
- avoid a future merge conflict 😉
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Update copyright holder in license

- api/catalog/api/controllers/search_controller.py
- api/catalog/api/examples/audio_responses.py
- api/catalog/api/examples/image_responses.py
- api/test/unit/controllers/test_search_controller.py
Fixes #196  by @dhruvkb 
This relatively simple change "truncates" the page count for a query to the current page number if we receive fewer results on the page than are able to fill out the page based on the page_size. This follows the suggestion from the issue by @AetherUnbound.
Checkout the branch and run the project according to the README.
Test the result views and pay attention to the page count. Test queries that have a single page, multiple pages, 20 pages, etc. Tip: use increasingly specific terms to get smaller returns from the test data.
Review the unit test cases added and confirm they are sensible.
<details>
``` …
```
> Make page_count self-truncating when we detect the last page of a query

- .github/dependabot.yml
Fixes #1046  by @krysal 
Some GH action dependencies are behind the latest updates:
+ actions/setup-python in CI + CD / Lint job
+ docker/setup-buildx-action in CI + CD / Build images (ingestion_server) job
+ etc.
Made changes in **dependabot.yml** so that GH dependencies are automatically updated.
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
> Update `dependabot.yml` to make Dependabot update GitHub actions

- api/Dockerfile
This PR is paired with enabling SSM on the API ECS cluster (https://github.com/WordPress/openverse-infrastructure/pull/374) - adding `screen` to the Django image will allow us to connect to the running ECS instance, launch a screen session, initiate a long-running command, and detach from the sessions without stopping the command. It will also enable any of the maintainers to access the running process, since anyone with SSM access can re-attach to the session.
This is similar in nature to how we've executed long-running processes on the API in the past. The only difference is that now this is done via ECS!
1. Build and start the stack: `just build && just up`
1. Exec into the running Django container: `just exec web bash`
1. Create a screen session: `screen -S foobar`
1. Run some …
> Add screen to API Docker image
